version: '3'

services:
  # Java API сервер
  java:
    build:
      context: ./DipServer
      dockerfile: Dockerfile
    container_name: java-server
    ports:
      - "8081:8081"
    volumes:
      - java_data:/app/data

  # Django приложение
  django:
    build:
      context: ./DipMain
      dockerfile: Dockerfile
    depends_on:
      - java
    environment:
      - DJANGO_SETTINGS_MODULE=Dip.settings
    command: python Dip/waitress_server.py

  # Nginx прокси-сервер
  nginx:
    image: nginx:alpine
    ports:
      - "8888:8888"
      - "9999:9999"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - django

volumes:
  java_data:
